"""SPDX SBOM generator contracts for the enforced dependency locks.

These tests prove strict lock-input validation (malformed entries refuse instead
of producing partial inventories), npm/Cargo identity resolution, purl
encoding, origin provenance and SPDX document metadata for
``scripts/release/generate_sboms.py``. They generate documents from fixture
locks only; they are not artifact-complete SBOM or G10 acceptance.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
for path in (ROOT, ROOT / "src"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from scripts.release import generate_sboms  # noqa: E402

SPDX_NAMESPACE_RE = re.compile(
    r"^https://eurogas-nexus\.invalid/spdx/eurogas-nexus-[a-z-]+-"
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
)
SPDX_TIMESTAMP_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")

DEFAULT_PYTHON_LOCK = "requests==2.32.3 \\\n    --hash=sha256:" + "0" * 64 + "\n"
PYTHON_LOCK_WITH_MARKERS = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    uv pip compile --python-version 3.11 --universal --generate-hashes pyproject.toml\n"
    "cffi==2.1.1 ; platform_python_implementation != 'PyPy' \\\n"
    "    --hash=sha256:" + "1" * 64 + " \\\n"
    "    --hash=sha256:" + "2" * 64 + "\n"
    "    # via eurogas-nexus (pyproject.toml)\n"
    "\n"
    "typing-extensions==4.16.0 ; python_full_version < '3.13' \\\n"
    "    --hash=sha256:" + "3" * 64 + "\n"
    "greenlet==3.5.5 ; sys_platform == 'win32' or sys_platform == 'linux' \\\n"
    "    --hash=sha256:" + "4" * 64 + "\n"
)
DEFAULT_WEB_PACKAGES: dict[str, Any] = {
    "": {"name": "eurogas-nexus-web", "version": "0.5.0"},
    "node_modules/left-pad": {"version": "1.3.0", "license": "WTFPL"},
}
DEFAULT_DESKTOP_PACKAGES: dict[str, Any] = {
    "": {"name": "eurogas-nexus-desktop", "version": "0.5.0"},
    "node_modules/@tauri-apps/cli": {"version": "2.8.4", "license": "MIT"},
}
DEFAULT_CARGO_ENTRIES: list[dict[str, Any]] = [
    {
        "name": "serde",
        "version": "1.0.219",
        "source": "registry+https://github.com/rust-lang/crates.io-index",
        "checksum": "9" * 64,
    }
]


def write_npm_lock(path: Path, packages: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {"name": "fixture", "version": "0.0.0", "lockfileVersion": 3, "packages": packages}
        ),
        encoding="utf-8",
    )


def write_cargo_lock(path: Path, entries: list[dict[str, Any]]) -> None:
    blocks = []
    for entry in entries:
        lines = ["[[package]]"]
        for key, value in entry.items():
            if isinstance(value, list):
                lines.append(f"{key} = [{', '.join(json.dumps(item) for item in value)}]")
            else:
                lines.append(f"{key} = {json.dumps(value)}")
        blocks.append("\n".join(lines))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("version = 4\n\n" + "\n\n".join(blocks) + "\n", encoding="utf-8")


def minimal_tree(root: Path) -> Path:
    """Write a complete, valid fixture lock tree."""
    root.mkdir(parents=True, exist_ok=True)
    (root / "requirements-runtime.lock").write_text(DEFAULT_PYTHON_LOCK, encoding="utf-8")
    write_npm_lock(root / "clients/web/package-lock.json", DEFAULT_WEB_PACKAGES)
    write_npm_lock(root / "clients/desktop/package-lock.json", DEFAULT_DESKTOP_PACKAGES)
    write_cargo_lock(root / "clients/desktop/src-tauri/Cargo.lock", DEFAULT_CARGO_ENTRIES)
    return root


def generate(root: Path, output: Path, monkeypatch: pytest.MonkeyPatch) -> int:
    """Run the generator against a fixture tree instead of the repository root."""
    monkeypatch.setattr(generate_sboms, "ROOT", root)
    return generate_sboms.main(
        ["--output-dir", str(output), "--notices", str(output / "THIRD_PARTY_NOTICES.md")]
    )


def test_nested_npm_entries_keep_last_segment_and_scoped_names(tmp_path: Path) -> None:
    root = minimal_tree(tmp_path)
    write_npm_lock(
        root / "clients/web/package-lock.json",
        {
            "": {"name": "eurogas-nexus-web", "version": "0.5.0"},
            "node_modules/@scope/tool": {"version": "2.0.0", "license": "MIT"},
            "node_modules/@scope/tool/node_modules/dup": {"version": "1.0.0", "license": "ISC"},
            "node_modules/dup": {"version": "0.9.0"},
            "node_modules/alias-dir": {"name": "real-package", "version": "3.0.0"},
            "node_modules/plain": {"name": "not a valid npm name", "version": "1.0.0"},
            "node_modules/linked": {"resolved": "packages/linked", "link": True},
        },
    )

    web = generate_sboms.npm_packages(root / "clients/web/package-lock.json")

    identities = [(item["name"], item["version"]) for item in web.packages]
    assert ("@scope/tool", "2.0.0") in identities
    assert ("dup", "1.0.0") in identities
    assert ("dup", "0.9.0") in identities
    assert ("real-package", "3.0.0") in identities
    # An invalid explicit name falls back to the derived last-segment identity.
    assert ("plain", "1.0.0") in identities
    # Workspace links and the project root are disclosed, never silently dropped.
    assert web.excluded == [
        {"spec": "", "reason": "project-package", "name": "eurogas-nexus-web"},
        {
            "spec": "node_modules/linked",
            "reason": "workspace-link",
            "name": "linked",
            "resolved": "packages/linked",
        },
    ]
    # Nested installs resolve to the package name, never to the nested path.
    assert all("node_modules" not in item["name"] for item in web.packages)
    assert sum(1 for item in web.packages if item["name"] == "dup") == 2

    purls = {(item["name"], item["version"]): item["purl"] for item in web.packages}
    assert purls[("@scope/tool", "2.0.0")] == "pkg:npm/%40scope/tool@2.0.0"
    assert purls[("dup", "1.0.0")] == "pkg:npm/dup@1.0.0"
    assert purls[("real-package", "3.0.0")] == "pkg:npm/real-package@3.0.0"


def test_purl_encoding_and_ecosystem_identity_rules() -> None:
    # npm names are lowercased but underscores are not rewritten.
    assert generate_sboms.build_purl("npm", "UPPER_Case", "1.0.0") == "pkg:npm/upper_case@1.0.0"
    # Cargo crate names keep their case and underscores; '+' is percent-encoded.
    assert (
        generate_sboms.build_purl("cargo", "MixedCase_Crate", "2.0.0+meta")
        == "pkg:cargo/MixedCase_Crate@2.0.0%2Bmeta"
    )
    # PyPI names use the PEP 503 canonical form: every [-_.] run collapses to '-'.
    assert (
        generate_sboms.build_purl("pypi", "My_Package.Name", "1.0rc1")
        == "pkg:pypi/my-package-name@1.0rc1"
    )
    assert generate_sboms.build_purl("pypi", "a-_.-B", "1.0") == "pkg:pypi/a-b@1.0"
    assert (
        generate_sboms.build_purl("pypi", "typing_extensions", "4.16.0")
        == "pkg:pypi/typing-extensions@4.16.0"
    )
    # npm scopes become a namespace that is lowercased and percent-encoded.
    assert (
        generate_sboms.build_purl("npm", "pkg", "1.0.0", namespace="@Scope")
        == "pkg:npm/%40scope/pkg@1.0.0"
    )
    # Structured quoting encodes separators instead of letting them through.
    assert generate_sboms.build_purl("npm", "odd/name", "1.0.0") == "pkg:npm/odd%2Fname@1.0.0"
    assert generate_sboms.build_purl("npm", "pkg", "1.0.0?a=b#c") == "pkg:npm/pkg@1.0.0%3Fa%3Db%23c"


def test_pypi_canonicalization_matches_installed_packaging() -> None:
    """Cross-check the PEP 503 rule against the upstream implementation."""
    packaging_utils = pytest.importorskip("packaging.utils")
    for name in ("My_Package.Name", "a-_.-B", "typing_extensions", "Zope.Interface", "a--b"):
        canonical = packaging_utils.canonicalize_name(name)
        assert generate_sboms.build_purl("pypi", name, "1.0") == f"pkg:pypi/{canonical}@1.0"


def test_cargo_lock_toml_reordered_keys_and_origin_provenance(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = minimal_tree(tmp_path)
    git_source = "git+https://example.invalid/org/dep?rev=deadbeef#deadbeefcafe"
    write_cargo_lock(
        root / "clients/desktop/src-tauri/Cargo.lock",
        [
            {
                "checksum": "a" * 64,
                "version": "1.4.0",
                "source": "registry+https://github.com/rust-lang/crates.io-index",
                "name": "reg-crate",
            },
            {"version": "0.2.0", "source": git_source, "name": "git-dep"},
            {"name": "path-dep", "version": "0.1.0"},
            {"name": "eurogas-nexus-desktop", "version": "0.5.0"},
        ],
    )

    packages, inputs = generate_sboms.collect_components(root=root)
    rust = {item["name"]: item for item in packages["desktop-rust"]}
    assert set(rust) == {"reg-crate", "git-dep", "path-dep"}
    assert rust["reg-crate"]["purl"] == "pkg:cargo/reg-crate@1.4.0"
    assert rust["reg-crate"]["checksum"] == "a" * 64
    assert rust["git-dep"]["origin"] == "git"
    assert "purl" not in rust["git-dep"]
    assert rust["path-dep"]["origin"] == "path"
    assert "purl" not in rust["path-dep"]

    cargo_input = next(item for item in inputs if item["component"] == "desktop-rust")
    assert cargo_input["origins"] == {
        "registry": 1,
        "registry-other": 0,
        "git": 1,
        "path": 1,
        "other": 0,
    }
    assert cargo_input["excluded_entries"] == [
        {
            "spec": "eurogas-nexus-desktop 0.5.0",
            "reason": "project-package",
            "name": "eurogas-nexus-desktop",
        }
    ]

    output = tmp_path / "sbom"
    assert generate(root, output, monkeypatch) == 0
    document = json.loads(
        (output / "eurogas-nexus-desktop-rust.spdx.json").read_text(encoding="utf-8")
    )
    by_name = {package["name"]: package for package in document["packages"]}
    assert by_name["reg-crate"]["checksums"] == [{"algorithm": "SHA256", "checksumValue": "a" * 64}]
    assert by_name["git-dep"]["sourceInfo"] == git_source
    locators = [
        ref["referenceLocator"]
        for package in document["packages"]
        for ref in package.get("externalRefs", [])
    ]
    # Only the crates.io crate carries a purl; git/path deps keep raw provenance.
    assert locators == ["pkg:cargo/reg-crate@1.4.0"]


def test_cargo_origin_requires_exact_canonical_crates_io_sources() -> None:
    assert (
        generate_sboms.cargo_origin("registry+https://github.com/rust-lang/crates.io-index")
        == "registry"
    )
    assert generate_sboms.cargo_origin("sparse+https://index.crates.io/") == "registry"
    assert generate_sboms.cargo_origin(None) == "path"
    assert generate_sboms.cargo_origin("git+https://example.invalid/org/dep") == "git"
    # Lookalike URLs that merely contain crates.io-index are not crates.io.
    for lookalike in (
        "registry+https://mirror.invalid/crates.io-index",
        "registry+https://github.com/rust-lang/crates.io-index/",
        "sparse+https://index.crates.io.invalid/",
        "sparse+https://index.crates.io",
    ):
        assert generate_sboms.cargo_origin(lookalike) == "registry-other", lookalike
    assert generate_sboms.cargo_origin("file:///srv/registry") == "other"


def test_cargo_lookalike_registry_sources_never_claim_crates_io(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = minimal_tree(tmp_path)
    lookalike = "registry+https://mirror.invalid/crates.io-index"
    write_cargo_lock(
        root / "clients/desktop/src-tauri/Cargo.lock",
        [
            {
                "name": "real-crate",
                "version": "1.0.0",
                "source": "sparse+https://index.crates.io/",
                "checksum": "b" * 64,
            },
            {
                "name": "lookalike",
                "version": "1.0.0",
                "source": lookalike,
                "checksum": "c" * 64,
            },
        ],
    )

    packages, inputs = generate_sboms.collect_components(root=root)
    rust = {item["name"]: item for item in packages["desktop-rust"]}
    assert rust["real-crate"]["origin"] == "registry"
    assert rust["real-crate"]["purl"] == "pkg:cargo/real-crate@1.0.0"
    assert rust["lookalike"]["origin"] == "registry-other"
    assert "purl" not in rust["lookalike"]
    assert rust["lookalike"]["source"] == lookalike

    cargo_input = next(item for item in inputs if item["component"] == "desktop-rust")
    assert cargo_input["origins"] == {
        "registry": 1,
        "registry-other": 1,
        "git": 0,
        "path": 0,
        "other": 0,
    }

    output = tmp_path / "sbom"
    assert generate(root, output, monkeypatch) == 0
    document = json.loads(
        (output / "eurogas-nexus-desktop-rust.spdx.json").read_text(encoding="utf-8")
    )
    locators = [
        ref["referenceLocator"]
        for package in document["packages"]
        for ref in package.get("externalRefs", [])
    ]
    assert locators == ["pkg:cargo/real-crate@1.0.0"]
    by_name = {package["name"]: package for package in document["packages"]}
    assert by_name["lookalike"]["sourceInfo"] == lookalike
    assert "checksums" in by_name["lookalike"]


@pytest.mark.parametrize(
    "entry",
    [
        {"name": "crate", "version": "1.0.0", "source": 42, "checksum": "a" * 64},
        {"name": "crate", "version": "1.0.0", "source": "", "checksum": "a" * 64},
        {
            "name": "crate",
            "version": "1.0.0",
            "source": "registry+https://github.com/rust-lang/crates.io-index",
            "checksum": "not-a-sha256-digest",
        },
        {
            "name": "crate",
            "version": "1.0.0",
            "source": "registry+https://github.com/rust-lang/crates.io-index",
            "checksum": 1234,
        },
        {
            "name": "crate",
            "version": "1.0.0",
            "source": "registry+https://github.com/rust-lang/crates.io-index",
            "checksum": "a" * 63,
        },
    ],
)
def test_cargo_wrong_typed_or_malformed_source_and_checksum_refuse(
    tmp_path: Path, entry: dict[str, Any]
) -> None:
    root = minimal_tree(tmp_path)
    write_cargo_lock(root / "clients/desktop/src-tauri/Cargo.lock", [entry])

    with pytest.raises(generate_sboms.SbomInputError) as error:
        generate_sboms.collect_components(root=root)
    message = str(error.value)
    assert "malformed 'source' field" in message or "malformed SHA256 'checksum'" in message


def test_missing_lock_inputs_fail_closed_without_outputs(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    empty_root = tmp_path / "empty"
    empty_root.mkdir()
    output = tmp_path / "sbom"

    assert generate(empty_root, output, monkeypatch) == 1
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is False
    joined = "\n".join(payload["errors"]).replace("\\", "/")
    assert "required lock input missing" in joined
    for relative in (
        "requirements-runtime.lock",
        "clients/web/package-lock.json",
        "clients/desktop/package-lock.json",
        "clients/desktop/src-tauri/Cargo.lock",
    ):
        assert relative in joined
    assert not output.exists()


def test_malformed_and_empty_required_inputs_are_rejected(tmp_path: Path) -> None:
    bad_json = minimal_tree(tmp_path / "bad-json")
    (bad_json / "clients/web/package-lock.json").write_text("{not json", encoding="utf-8")
    with pytest.raises(generate_sboms.SbomInputError) as json_error:
        generate_sboms.collect_components(root=bad_json)
    assert "invalid JSON" in str(json_error.value)

    bad_toml = minimal_tree(tmp_path / "bad-toml")
    (bad_toml / "clients/desktop/src-tauri/Cargo.lock").write_text(
        "[[package]\nname = ", encoding="utf-8"
    )
    with pytest.raises(generate_sboms.SbomInputError) as toml_error:
        generate_sboms.collect_components(root=bad_toml)
    assert "invalid TOML" in str(toml_error.value)

    zero_byte = minimal_tree(tmp_path / "zero-byte")
    (zero_byte / "clients/desktop/package-lock.json").write_text("", encoding="utf-8")
    with pytest.raises(generate_sboms.SbomInputError) as empty_error:
        generate_sboms.collect_components(root=zero_byte)
    assert "invalid JSON" in str(empty_error.value)

    no_npm_packages = minimal_tree(tmp_path / "empty-npm")
    write_npm_lock(
        no_npm_packages / "clients/web/package-lock.json",
        {"": {"name": "eurogas-nexus-web", "version": "0.5.0"}},
    )
    with pytest.raises(generate_sboms.SbomInputError) as npm_error:
        generate_sboms.collect_components(root=no_npm_packages)
    assert "no third-party packages" in str(npm_error.value)

    no_cargo_array = minimal_tree(tmp_path / "empty-cargo")
    (no_cargo_array / "clients/desktop/src-tauri/Cargo.lock").write_text(
        "version = 4\n", encoding="utf-8"
    )
    with pytest.raises(generate_sboms.SbomInputError) as cargo_error:
        generate_sboms.collect_components(root=no_cargo_array)
    assert "missing 'package' array" in str(cargo_error.value)

    no_python_packages = minimal_tree(tmp_path / "empty-python")
    (no_python_packages / "requirements-runtime.lock").write_text(
        "eurogas-nexus==0.5.0 \\\n    --hash=sha256:" + "0" * 64 + "\n", encoding="utf-8"
    )
    with pytest.raises(generate_sboms.SbomInputError) as python_error:
        generate_sboms.collect_components(root=no_python_packages)
    assert "no third-party packages" in str(python_error.value)

    bad_identity = minimal_tree(tmp_path / "bad-identity")
    write_npm_lock(
        bad_identity / "clients/web/package-lock.json",
        {"node_modules/bad name": {"version": "1.0.0"}},
    )
    with pytest.raises(generate_sboms.SbomInputError) as identity_error:
        generate_sboms.collect_components(root=bad_identity)
    assert "cannot resolve npm package identity" in str(identity_error.value)


@pytest.mark.parametrize(
    "broken_entry",
    [
        "1.3.0",
        {"license": "MIT"},
        {"version": 1},
        {"version": ""},
        {"version": "1.3.0", "link": "yes"},
    ],
)
def test_malformed_npm_entries_refuse_instead_of_partial_inventory(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
    broken_entry: Any,
) -> None:
    root = minimal_tree(tmp_path)
    write_npm_lock(
        root / "clients/web/package-lock.json",
        {
            "": {"name": "eurogas-nexus-web", "version": "0.5.0"},
            "node_modules/left-pad": {"version": "1.3.0", "license": "WTFPL"},
            "node_modules/broken": broken_entry,
        },
    )

    # A malformed entry next to valid ones fails the whole parse.
    with pytest.raises(generate_sboms.SbomInputError) as error:
        generate_sboms.collect_components(root=root)
    assert "malformed npm lock entry 'node_modules/broken'" in str(error.value)

    output = tmp_path / "sbom"
    assert generate(root, output, monkeypatch) == 1
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is False
    assert not output.exists()


def test_npm_workspace_links_are_disclosed_not_silently_omitted(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = minimal_tree(tmp_path)
    write_npm_lock(
        root / "clients/web/package-lock.json",
        {
            "": {"name": "eurogas-nexus-web", "version": "0.5.0"},
            "node_modules/left-pad": {"version": "1.3.0", "license": "WTFPL"},
            "node_modules/@scope/linked": {"resolved": "packages/linked", "link": True},
        },
    )

    inventory = generate_sboms.npm_packages(root / "clients/web/package-lock.json")
    assert [item["name"] for item in inventory.packages] == ["left-pad"]
    assert inventory.excluded == [
        {"spec": "", "reason": "project-package", "name": "eurogas-nexus-web"},
        {
            "spec": "node_modules/@scope/linked",
            "reason": "workspace-link",
            "name": "@scope/linked",
            "resolved": "packages/linked",
        },
    ]

    output = tmp_path / "sbom"
    assert generate(root, output, monkeypatch) == 0
    manifest = json.loads((output / "sbom-manifest.json").read_text(encoding="utf-8"))
    inputs = {item["component"]: item for item in manifest["inputs"]}
    assert inputs["web-node"]["packages"] == 1
    assert inputs["web-node"]["excluded_entries"] == inventory.excluded
    assert "excluded_entries" in manifest["inventory_scope"]
    notices = (output / "THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")
    assert "link: true" in notices


def test_python_lock_accepts_multiline_hashes_comments_and_markers(tmp_path: Path) -> None:
    root = minimal_tree(tmp_path)
    (root / "requirements-runtime.lock").write_text(PYTHON_LOCK_WITH_MARKERS, encoding="utf-8")

    inventory = generate_sboms.python_packages(root / "requirements-runtime.lock")
    assert [(item["name"], item["version"]) for item in inventory.packages] == [
        ("cffi", "2.1.1"),
        ("typing-extensions", "4.16.0"),
        ("greenlet", "3.5.5"),
    ]
    assert inventory.packages[0]["purl"] == "pkg:pypi/cffi@2.1.1"
    assert inventory.excluded == []


@pytest.mark.parametrize(
    "declaration",
    [
        # URLs, editables and ranges are not pins.
        "requests @ https://example.invalid/requests-2.32.3.tar.gz",
        "-e ./vendor/requests",
        "requests>=2.31",
        "requests~=2.32",
        "requests",
        "requests===2.32.3",
        # Truncated or extended declarations must not be half-parsed.
        "requests==2.32.3;bogus",
        "requests==2.32.3 trailing-junk",
        "requests==2.32.3  # inline comment",
        "requests==2.32.3 ; os_name = 'nt'",
        "requests==2.32.3 ; sys_platform like 'win32'",
        # Hash entries must be well formed and belong to the declaration.
        "requests==2.32.3 --index-url https://example.invalid/simple",
        "requests==2.32.3",
        "requests==2.32.3 \\\n    --hash=sha256:abcd",
        "requests==2.32.3 \\\n    --hash=md5:" + "0" * 64,
        "requests==2.32.3 \\\n    --hash=blake2b:" + "0" * 128,
        "requests==2.32.3 \\\n    --hash=sha256:" + "a" * 64 + " \\",
        "--extra-index-url https://example.invalid/simple",
        "requests==2.32.3 \\\n\n    --hash=sha256:" + "a" * 64,
    ],
)
def test_python_lock_refuses_anything_it_cannot_fully_parse(
    tmp_path: Path, declaration: str
) -> None:
    root = minimal_tree(tmp_path)
    (root / "requirements-runtime.lock").write_text(declaration + "\n", encoding="utf-8")

    with pytest.raises(generate_sboms.SbomInputError):
        generate_sboms.collect_components(root=root)


def test_python_lock_unknown_lines_never_yield_partial_success(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    root = minimal_tree(tmp_path)
    (root / "requirements-runtime.lock").write_text(
        DEFAULT_PYTHON_LOCK + "--extra-index-url https://example.invalid/simple\n",
        encoding="utf-8",
    )

    with pytest.raises(generate_sboms.SbomInputError) as error:
        generate_sboms.collect_components(root=root)
    assert "unsupported or malformed requirement" in str(error.value)

    output = tmp_path / "sbom"
    assert generate(root, output, monkeypatch) == 1
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is False
    assert not output.exists()


def test_python_lock_excludes_project_packages_as_disclosed_entries(tmp_path: Path) -> None:
    root = minimal_tree(tmp_path)
    (root / "requirements-runtime.lock").write_text(
        "Eurogas_Nexus==0.5.0 \\\n    --hash=sha256:" + "0" * 64 + "\n"
        "requests==2.32.3 \\\n    --hash=sha256:" + "1" * 64 + "\n",
        encoding="utf-8",
    )

    inventory = generate_sboms.python_packages(root / "requirements-runtime.lock")
    assert [item["name"] for item in inventory.packages] == ["requests"]
    assert inventory.excluded == [
        {"spec": "Eurogas_Nexus==0.5.0", "reason": "project-package", "name": "Eurogas_Nexus"}
    ]


def test_manifest_records_lock_hashes_and_inventory_scope(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = minimal_tree(tmp_path)
    output = tmp_path / "sbom"
    assert generate(root, output, monkeypatch) == 0

    manifest = json.loads((output / "sbom-manifest.json").read_text(encoding="utf-8"))
    assert set(manifest["components"]) == {
        "python-runtime",
        "web-node",
        "desktop-node",
        "desktop-rust",
    }
    # No per-artifact mapping is claimed by this generator.
    assert manifest["artifacts"] == {}

    inputs = {item["path"]: item for item in manifest["inputs"]}
    assert set(inputs) == {
        "requirements-runtime.lock",
        "clients/web/package-lock.json",
        "clients/desktop/package-lock.json",
        "clients/desktop/src-tauri/Cargo.lock",
    }
    for relative, item in inputs.items():
        payload = (root / relative).read_bytes()
        assert item["sha256"] == hashlib.sha256(payload).hexdigest()
        assert item["size_bytes"] == len(payload)
        assert item["packages"] > 0
        assert "excluded_entries" in item

    # The recorded hash follows the lock bytes, not a normalized re-rendering.
    original = (root / "requirements-runtime.lock").read_bytes()
    (root / "requirements-runtime.lock").write_bytes(original + b"\n# trailing comment\n")
    _, updated_inputs = generate_sboms.collect_components(root=root)
    updated = next(item for item in updated_inputs if item["component"] == "python-runtime")
    assert updated["sha256"] != inputs["requirements-runtime.lock"]["sha256"]

    scope = manifest["inventory_scope"]
    assert scope["basis"] == "dependency-locks"
    assert scope["includes_dev_and_build_dependencies"] is True
    assert "all platforms" in scope["target_over_inclusion"]
    assert "NOASSERTION" in scope["license_metadata"]
    assert any("container image" in item for item in scope["missing_inventory"])
    assert any("binaries" in item for item in scope["missing_inventory"])
    assert "license texts" in scope["notices_scope"]
    assert "G10" in scope["acceptance_note"]

    counts = manifest["component_packages"]
    assert counts["web-node"]["packages"] == len(DEFAULT_WEB_PACKAGES) - 1
    assert counts["desktop-node"]["packages"] == len(DEFAULT_DESKTOP_PACKAGES) - 1
    assert counts["desktop-rust"]["packages"] == len(DEFAULT_CARGO_ENTRIES)
    assert counts["python-runtime"]["packages"] == 1


def test_document_namespaces_are_unique_and_timestamps_are_spdx_utc(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = minimal_tree(tmp_path)
    outputs = (tmp_path / "first", tmp_path / "second")
    for output in outputs:
        assert generate(root, output, monkeypatch) == 0

    namespaces: list[str] = []
    for output in outputs:
        documents = sorted(output.glob("eurogas-nexus-*.spdx.json"))
        assert len(documents) == 4
        for path in documents:
            document = json.loads(path.read_text(encoding="utf-8"))
            assert document["spdxVersion"] == "SPDX-2.3"
            assert document["dataLicense"] == "CC0-1.0"
            assert document["SPDXID"] == "SPDXRef-DOCUMENT"
            namespace = document["documentNamespace"]
            assert SPDX_NAMESPACE_RE.match(namespace), namespace
            namespaces.append(namespace)
            created = document["creationInfo"]["created"]
            assert SPDX_TIMESTAMP_RE.match(created), created
            parsed = datetime.strptime(created, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=UTC)
            assert abs((datetime.now(UTC) - parsed).total_seconds()) < 300
            assert len(document["packages"]) == len(document["relationships"])
            assert document["relationships"]
    assert len(namespaces) == len(set(namespaces)) == 8


def test_release_manifest_consumer_mapping_is_unchanged(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = minimal_tree(tmp_path)
    output = tmp_path / "sbom"
    assert generate(root, output, monkeypatch) == 0

    artifacts_dir = tmp_path / "artifacts"
    artifacts_dir.mkdir()
    (artifacts_dir / "Eurogas-Nexus-Client-1.2.3-windows-x64-setup.exe").write_bytes(b"fixture")

    from scripts.release.build_release_manifest import build_manifest

    context = {
        "product_name": "Eurogas Nexus",
        "app_version": "1.2.3",
        "release_version": "v1.2.3",
        "channel": "preview",
        "git_sha": "0" * 40,
        "git_ref": "refs/heads/main",
        "build_run_id": "123",
        "build_timestamp": "2026-09-28T00:00:00Z",
        "source_repository": "AlexYuhuFeng/EurogasNexus",
        "database_schema_revision": "0036_job_records",
        "api_image": "ghcr.io/alexyuhufeng/eurogasnexus-api",
    }
    manifest = build_manifest(context, artifacts_dir, sbom_dir=output)

    # The sbom manifest previously never mapped artifact names; consumers keep
    # observing an empty per-artifact reference list.
    assert [item["sbom_ref"] for item in manifest["artifacts"]] == [[]]
    assert {item["name"] for item in manifest["sbom_files"]} == {
        "eurogas-nexus-python-runtime.spdx.json",
        "eurogas-nexus-web-node.spdx.json",
        "eurogas-nexus-desktop-node.spdx.json",
        "eurogas-nexus-desktop-rust.spdx.json",
    }
    for item in manifest["sbom_files"]:
        payload = (output / item["name"]).read_bytes()
        assert item["sha256"] == hashlib.sha256(payload).hexdigest()


def test_notices_disclose_scope_and_unknown_licenses(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = minimal_tree(tmp_path)
    output = tmp_path / "sbom"
    assert generate(root, output, monkeypatch) == 0

    text = (output / "THIRD_PARTY_NOTICES.md").read_text(encoding="utf-8")
    assert "@tauri-apps/cli 2.8.4 (MIT)" in text
    assert "requests 2.32.3 (NOASSERTION)" in text
    assert "unknown (`NOASSERTION`)" in text
    assert "not a legal review" in text
    assert "container image" in text
    assert "dev/optional" in text
