"""Route-cost enum contracts."""

from __future__ import annotations

from enum import StrEnum


class TariffStatus(StrEnum):
    FINAL = "FINAL"
    INDICATIVE = "INDICATIVE"
    PROVISIONAL = "PROVISIONAL"
    DRAFT = "DRAFT"
    SIMULATOR_ONLY = "SIMULATOR_ONLY"


class TariffDirection(StrEnum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"


class CapacityProduct(StrEnum):
    ANNUAL = "ANNUAL"
    QUARTERLY = "QUARTERLY"
    MONTHLY = "MONTHLY"
    WEEKLY = "WEEKLY"
    DAILY = "DAILY"
    WITHIN_DAY = "WITHIN_DAY"


class Firmness(StrEnum):
    FIRM = "FIRM"
    INTERRUPTIBLE = "INTERRUPTIBLE"
    BACKHAUL = "BACKHAUL"
    OFF_PEAK = "OFF_PEAK"


class PointType(StrEnum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    BEACH = "BEACH"
    LNG_TERMINAL = "LNG_TERMINAL"
    STORAGE = "STORAGE"
    INTERCONNECTION = "INTERCONNECTION"
    VIRTUAL = "VIRTUAL"
    OFFTAKE = "OFFTAKE"


class BusinessModel(StrEnum):
    VIRTUAL_HUB_SALE = "VIRTUAL_HUB_SALE"
    PHYSICAL_DELIVERY = "PHYSICAL_DELIVERY"
    STORAGE_INJECTION = "STORAGE_INJECTION"
    CROSS_BORDER_TRANSFER = "CROSS_BORDER_TRANSFER"


class DeliveryMode(StrEnum):
    TERMINAL_TITLE_TRANSFER = "TERMINAL_TITLE_TRANSFER"
    VIRTUAL_HUB_SALE = "VIRTUAL_HUB_SALE"
    PHYSICAL_ENTRY_DELIVERY = "PHYSICAL_ENTRY_DELIVERY"
    DOWNSTREAM_PHYSICAL_DELIVERY = "DOWNSTREAM_PHYSICAL_DELIVERY"
    BORDER_TRANSFER = "BORDER_TRANSFER"
    STORAGE_INJECTION = "STORAGE_INJECTION"
    STORAGE_WITHDRAWAL = "STORAGE_WITHDRAWAL"


class SourceResourceType(StrEnum):
    BEACH_DELIVERY = "BEACH_DELIVERY"
    LNG_REGAS = "LNG_REGAS"
    PIPELINE_IMPORT = "PIPELINE_IMPORT"
    STORAGE = "STORAGE"
    CONTRACT_POOL = "CONTRACT_POOL"


class CostComponentType(StrEnum):
    ENTRY_CAPACITY = "ENTRY_CAPACITY"
    EXIT_CAPACITY = "EXIT_CAPACITY"
    COMMODITY_CHARGE = "COMMODITY_CHARGE"
    BALANCING_ALLOWANCE = "BALANCING_ALLOWANCE"
    AUCTION_PREMIUM = "AUCTION_PREMIUM"
    CASHFLOW_TIMING = "CASHFLOW_TIMING"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
