"""Agent-native research contracts (CR-15)."""

from eurogas_nexus.domain.agents.challenge import ChallengeReport, ChallengeResult
from eurogas_nexus.domain.agents.contracts import (
    DEFAULT_AGENT_PROFILES,
    PROFILES_BY_ID,
    ActionPolicy,
    AgentContext,
    AgentInvocationContext,
    AgentProfile,
    AgentRunStatus,
    CapabilityDefinition,
    CapabilityDomain,
    CapabilityFailure,
    CapabilityFailureCode,
    CapabilityRelationship,
    CapabilityResult,
    CapabilityStatus,
    DeterminismClass,
    IdempotencyClass,
    OrchestrationStage,
    RetryPolicy,
    SideEffectClass,
)

__all__ = [
    "DEFAULT_AGENT_PROFILES",
    "PROFILES_BY_ID",
    "ActionPolicy",
    "ChallengeReport",
    "ChallengeResult",
    "AgentContext",
    "AgentInvocationContext",
    "AgentProfile",
    "AgentRunStatus",
    "CapabilityDefinition",
    "CapabilityDomain",
    "CapabilityFailure",
    "CapabilityFailureCode",
    "CapabilityRelationship",
    "CapabilityResult",
    "CapabilityStatus",
    "DeterminismClass",
    "IdempotencyClass",
    "OrchestrationStage",
    "RetryPolicy",
    "SideEffectClass",
]
