"""Add CR-15 agent capability and research orchestration tables.

Revision ID: 0032_agent_capability_layer
Revises: 0031_research_data_foundation
Create Date: 2026-09-07
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0032_agent_capability_layer"
down_revision = "0031_research_data_foundation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("agent_run_id", sa.String(length=128), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=False),
        sa.Column("agent_profile", sa.String(length=32), nullable=False),
        sa.Column("model_provider", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("user_objective", sa.Text(), nullable=False),
        sa.Column("research_plan_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_stage", sa.String(length=32), nullable=False),
        sa.Column("artifacts_created", sa.JSON(), nullable=False),
        sa.Column("evidence_dependencies", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("blockers", sa.JSON(), nullable=False),
        sa.Column("token_cost_metadata", sa.JSON(), nullable=False),
        sa.Column("final_output_reference", sa.String(length=256), nullable=True),
        sa.Column("correlation_request_id", sa.String(length=64), nullable=True),
        sa.Column("agent_runtime_version", sa.String(length=32), nullable=False),
        sa.Column("started_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("agent_run_id"),
    )
    op.create_index(
        "ix_agent_runs_principal_created",
        "agent_runs",
        ["principal_id", "created_at_utc"],
        unique=False,
    )
    op.create_index("ix_agent_runs_status", "agent_runs", ["status"], unique=False)
    op.create_table(
        "agent_challenge_reports",
        sa.Column("challenge_report_id", sa.String(length=128), nullable=False),
        sa.Column("agent_run_id", sa.String(length=128), nullable=True),
        sa.Column("strategy_version_id", sa.String(length=128), nullable=True),
        sa.Column("backtest_run_id", sa.String(length=128), nullable=True),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("overall_result", sa.String(length=32), nullable=False),
        sa.Column("recommended_follow_up", sa.Text(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.agent_run_id"],
        ),
        sa.PrimaryKeyConstraint("challenge_report_id"),
    )
    op.create_index(
        "ix_agent_challenge_reports_version",
        "agent_challenge_reports",
        ["strategy_version_id"],
        unique=False,
    )
    op.create_table(
        "agent_research_budgets",
        sa.Column("budget_id", sa.String(length=128), nullable=False),
        sa.Column("agent_run_id", sa.String(length=128), nullable=True),
        sa.Column("max_hypotheses", sa.Integer(), nullable=False),
        sa.Column("max_parameter_variants", sa.Integer(), nullable=False),
        sa.Column("max_backtest_runs", sa.Integer(), nullable=False),
        sa.Column("max_llm_calls", sa.Integer(), nullable=False),
        sa.Column("time_budget_seconds", sa.Integer(), nullable=False),
        sa.Column("token_budget", sa.Integer(), nullable=False),
        sa.Column("hypotheses_used", sa.Integer(), nullable=False),
        sa.Column("parameter_variants_used", sa.Integer(), nullable=False),
        sa.Column("backtest_runs_used", sa.Integer(), nullable=False),
        sa.Column("llm_calls_used", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("selection_criterion", sa.String(length=128), nullable=False),
        sa.Column("final_holdout_period", sa.JSON(), nullable=False),
        sa.Column("final_holdout_inspections", sa.Integer(), nullable=False),
        sa.Column("max_final_holdout_inspections", sa.Integer(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.agent_run_id"],
        ),
        sa.PrimaryKeyConstraint("budget_id"),
    )
    op.create_table(
        "agent_research_findings",
        sa.Column("finding_id", sa.String(length=128), nullable=False),
        sa.Column("research_plan_id", sa.String(length=128), nullable=True),
        sa.Column("agent_run_id", sa.String(length=128), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("statistic", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=128), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("sample", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=64), nullable=False),
        sa.Column("methodology", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("quality_state", sa.String(length=32), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.agent_run_id"],
        ),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index(
        "ix_agent_research_findings_plan",
        "agent_research_findings",
        ["research_plan_id"],
        unique=False,
    )
    op.create_table(
        "agent_research_plans",
        sa.Column("research_plan_id", sa.String(length=128), nullable=False),
        sa.Column("agent_run_id", sa.String(length=128), nullable=True),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("market_scope", sa.JSON(), nullable=False),
        sa.Column("entities", sa.JSON(), nullable=False),
        sa.Column("product", sa.String(length=32), nullable=False),
        sa.Column("horizon", sa.String(length=16), nullable=False),
        sa.Column("hypotheses_to_test", sa.JSON(), nullable=False),
        sa.Column("required_evidence", sa.JSON(), nullable=False),
        sa.Column("analyses", sa.JSON(), nullable=False),
        sa.Column("data_quality_requirements", sa.JSON(), nullable=False),
        sa.Column("statistical_requirements", sa.JSON(), nullable=False),
        sa.Column("strategy_generation_allowed", sa.Boolean(), nullable=False),
        sa.Column("stopping_conditions", sa.JSON(), nullable=False),
        sa.Column("validation_issues", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.agent_run_id"],
        ),
        sa.PrimaryKeyConstraint("research_plan_id"),
    )
    op.create_table(
        "agent_review_packs",
        sa.Column("review_pack_id", sa.String(length=128), nullable=False),
        sa.Column("agent_run_id", sa.String(length=128), nullable=True),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("research_plan", sa.JSON(), nullable=False),
        sa.Column("key_findings", sa.JSON(), nullable=False),
        sa.Column("strategy_specification", sa.JSON(), nullable=True),
        sa.Column("backtest", sa.JSON(), nullable=True),
        sa.Column("robustness", sa.JSON(), nullable=False),
        sa.Column("challenge_report", sa.JSON(), nullable=True),
        sa.Column("data_provenance", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("known_limitations", sa.JSON(), nullable=False),
        sa.Column("alternative_hypotheses", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.agent_run_id"],
        ),
        sa.PrimaryKeyConstraint("review_pack_id"),
    )
    op.create_index(
        "ix_agent_review_packs_run", "agent_review_packs", ["agent_run_id"], unique=False
    )
    op.create_table(
        "agent_tool_invocations",
        sa.Column("invocation_id", sa.String(length=128), nullable=False),
        sa.Column("agent_run_id", sa.String(length=128), nullable=True),
        sa.Column("capability_id", sa.String(length=128), nullable=False),
        sa.Column("capability_version", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=False),
        sa.Column("started_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("input_summary", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("output_reference", sa.String(length=256), nullable=True),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("entitlement_state", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.agent_run_id"],
        ),
        sa.PrimaryKeyConstraint("invocation_id"),
    )
    op.create_index(
        "ix_agent_tool_invocations_capability",
        "agent_tool_invocations",
        ["capability_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_tool_invocations_run", "agent_tool_invocations", ["agent_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in (
        "agent_review_packs",
        "agent_challenge_reports",
        "agent_research_budgets",
        "agent_research_findings",
        "agent_research_plans",
        "agent_tool_invocations",
        "agent_runs",
    ):
        op.drop_table(table)
