"""Freeze the exact installed dependency versions into requirements.lock.

Reads ``*.dist-info/METADATA`` from an installed site-packages directory
(default ``.deps``) and writes ``name==version`` lines, sorted, with a header.
The lock is a deployment artifact: CI and release builds should install from
it so the audited versions are the shipped versions.

Usage:
    python scripts/ci/freeze_lock.py [site_packages_dir] [output_path]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

VERSION_RE = re.compile(r"^Version:\s*(.+)$")
NAME_RE = re.compile(r"^Name:\s*(.+)$")


def _dist_names(site_packages: Path) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for metadata_path in site_packages.glob("*.dist-info/METADATA"):
        name = ""
        version = ""
        for line in metadata_path.read_text(encoding="utf-8", errors="replace").splitlines():
            name_match = NAME_RE.match(line)
            if name_match and not name:
                name = name_match.group(1).strip()
            version_match = VERSION_RE.match(line)
            if version_match and not version:
                version = version_match.group(1).strip()
            if name and version:
                break
        if not name:
            name = metadata_path.parent.name.removesuffix(".dist-info")
        entries.append((name, version))
    return sorted(entries)


def freeze(site_packages: Path, output: Path) -> int:
    """    Freeze installed distributions into a pinned lock file.

    Returns:
        Exit code: 0 written, 1 on failure."""
    entries = _dist_names(site_packages)
    if not entries:
        print(f"no dist-info found in {site_packages}")
        return 2
    lines = [
        "# Eurogas Nexus dependency lock (exact versions).",
        "# Generated by scripts/ci/freeze_lock.py from installed site-packages.",
        f"# Source: {site_packages}",
        "",
    ]
    lines.extend(f"{name}=={version}" if version else name for name, version in entries)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(entries)} pinned requirements to {output}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """    CLI entry point for the lock freeze."""
    args = list(argv) if argv is not None else sys.argv[1:]
    site_packages = Path(args[0]) if args else Path(".deps")
    output = Path(args[1]) if len(args) > 1 else Path("requirements.lock")
    if not site_packages.is_dir():
        print(f"site-packages directory not found: {site_packages}")
        return 2
    return freeze(site_packages, output)


if __name__ == "__main__":
    raise SystemExit(main())
