import type { ContractDraft } from "./defaultContractDraft";

export function buildContractPayload(contract: ContractDraft) {
  return {
    contract_id: contract.contract_id.trim() || "operator-ttf-supply-2025",
    contract_name: contract.contract_name.trim() || contract.contract_id.trim() || "Operator supply contract",
    resource_type: "PIPELINE_IMPORT",
    delivery_point_name: contract.delivery_point_name.trim() || "TTF",
    gas_year: contract.gas_year.trim() || "2025+",
    delivery_quantity_mwh_per_day: contract.delivery_quantity_mwh_per_day,
    contract_price_gbp_mwh: contract.contract_price_gbp_mwh,
    settlement_frequency: contract.settlement_frequency,
    upstream_payment_lag_days: contract.upstream_payment_lag_days,
    screen_sale_cash_lag_days: contract.screen_sale_cash_lag_days,
    delivery_tolerance_pct: contract.delivery_tolerance_pct,
    nomination_tolerance_pct: contract.nomination_tolerance_pct,
    tolerance_risk_allowance_gbp_mwh: contract.tolerance_risk_allowance_gbp_mwh,
    annual_financing_rate_pct: contract.annual_financing_rate_pct,
    owned_entry_capacity_mwh_per_day: contract.owned_entry_capacity_mwh_per_day,
    owned_exit_capacity_mwh_per_day: contract.owned_exit_capacity_mwh_per_day,
    allowed_exit_points: contract.allowed_exit_points,
    eligible_sale_modes: contract.eligible_sale_modes,
    notes: JSON.stringify({
      source: "web_contract_capture",
      decision_support_only: true,
      human_review_required: true,
      counterparty: contract.counterparty,
      contract_type: contract.contract_type,
      title_transfer_point: contract.title_transfer_point,
      beach_delivery_point: contract.beach_delivery_point,
      index_basis: contract.index_basis,
      terminal_access: contract.terminal_access,
      capacity_expiry: contract.capacity_expiry,
      document_name: contract.document_name,
      document_status: contract.document_status,
      source_reference: contract.source_reference,
      governing_law: contract.governing_law,
      physical_exit_point_name: contract.physical_exit_point_name,
      variable_cost_gbp_mwh: contract.variable_cost_gbp_mwh,
      regas_fee_gbp_mwh: contract.regas_fee_gbp_mwh,
      fuel_loss_allowance_pct: contract.fuel_loss_allowance_pct,
    }),
  };
}
